### PR TITLE
Upgraded Unit-1 / Lesson 6 to Akka.FSharp 1.2.0

### PR DESCRIPTION
**Pull request by Youenn-Bouglouan**
And this is the last lesson of Unit 1. There was no need to touch the README file this time.

- Upgraded Akka.FSharp version from 1.0.4 to 1.2.0
- Replaced obsolete calls to System.Shutdown() by calls to System.Terminate()
- Replaced obsolete calls to System.AwaitTermination() by calls to System.WhenTerminated.Wait()

### CODE REVIEW

**Comment by Aaronontheweb** [comment]
@Youenn-Bouglouan if we can get the whole bootcamp ported to F#, going to re-release this thing with a new organization that has C# / F# paths clearly advertised from the beginning

**Comment by Youenn-Bouglouan** [comment]
@Aaronontheweb I haven't looked at the C# bootcamp at all to be honest. Do you know more or less what is missing from the F# one? Whole lessons or just smaller parts? I could try to add those if I can. 
I just started Unit 2.

**Comment by Aaronontheweb** [comment]
@Youenn-Bouglouan I think some of Unit 2 and all of unit 3 is missing

**Comment by Youenn-Bouglouan** [comment]
@Aaronontheweb Ok cool then, I'll compare both versions as I go along :).

**Pull request merged**
