### PR TITLE
Upgraded Unit-1's DoThis and Lesson1 to Akka.FSharp 1.2.0

### PR DESCRIPTION
**Pull request by Youenn-Bouglouan**
Changes applied to **Unit-1**'s **DoThis** and **lesson1**:
- Upgraded Akka.FSharp version from 1.0.4 to 1.2.0
- replaced obsolete calls to System.Shutdown() by calls to System.Terminate()
- replaced obsolete calls to System.AwaitTermination() by calls to System.WhenTerminated.Wait()

### CODE REVIEW

**Comment by Aaronontheweb** [comment]
thanks for your contribution @Youenn-Bouglouan ! much appreciated!

**Comment by Youenn-Bouglouan** [comment]
You're welcome @Aaronontheweb ! I plan on upgrading the other lessons as I progress through the bootcamp. Out of curiosity, would you prefer having one PR per lesson, or just one big PR for the whole unit?

**Comment by Aaronontheweb** [comment]
Much easier to do one per lesson - makes it easier for me and others on the Petabridge team to review.

**Comment by Youenn-Bouglouan** [comment]
Alright then, sounds better to me too.

**Pull request merged**
