### PR TITLE
Port to net5

### PR DESCRIPTION
**Pull request by vilinski**
Ported all lessons to `net5` framework, which should be a future of .NET, proposally released at November 2020.

Note that `System.Windows.Forms.DataVisualization` used in `Unit-2` is deprecated, gets no updates anymore, but still usable. The last available version (2020-06), compatible with .NET Core, is `1.0.0-prerelease.20110.1`

### CODE REVIEW

**Comment by vilinski** [comment]
I have some of commits with no author settings in git, So I cannot sign your CLA twice. Should I care?

**Comment by Aaronontheweb** [comment]
@vilinski nope, so long as you're fine with us merging in this PR.

This is _amazing_ - I'm going to have a member of our team look at it briefly since we were planning on updating everything this summer to run on .NET Core, but this is a fantastic jump ahead to the latest and greatest.

**Comment by Aaronontheweb** [comment]
For Akka.NET? Definitely not - we have thousands of users who would love to move off of .NET Framework, but can't just yet because those software systems are doing critical things like running live banking / healthcare / transit infrastructure and migrating requires a very large amount of risk management. We're committed to supporting those users.

For Akka.NET bootcamp - I don't think it matters as much here since this is meant to be a set of learning exercises. Do you agree?

**Comment by snekbaev** [comment]
@Aaronontheweb that's basically what I thought, but life has taught me that it's always good to confirm. Thank you! :)

**Comment by Aaronontheweb** [comment]
Always good to ask and I'm happy to answer :)

**Comment by Aaronontheweb** [comment]
Going to go through and review this next week - very excited to check it out.

**Comment by vilinski** [comment]
glad you like it! )) Main purpose was to introduce an actor system to my collegues, because our development is .NET Core only. Surely I'm fine with any merges or anything you think is right

Actually there was not much work, what you evtl. expect, and was as easy as

- remove all csproj and config files
- `dotnet new winforms` in each DoThis folder
- add `akka` and other NuGets until it compiles again
- hardcode some hocon

Despite `net5` it is still windows-only because of not completely cross plattform windows forms.

**Comment by sambeckingham** [comment]
Unit-2, Lesson 1 is not right.  The state of the project in DoThis is different.

1. The HOCON string is now in a property in Program.cs
1. There is no app.config
1. The application no longer throws an exception in its default state

I feel this is important, the exception was meant for demonstrative and educational purposes.  I'm running through this lesson as someone new to Akka.NET now and I have no idea if Akka or .NET 5 has fixed its threading in such a way that the issues discussed in Lesson 1 no longer apply.

Could we possibly reintroduce the broken functionality or if it's no longer possible, can we update the context of the lesson to describe dispatchers with the new behaviour taken into consideration?

(Unit 1 is absolutely fine, as an aside 👍 )

**Comment by vilinski** [comment]
Hi, @sambeckingham, thanks for looking at this. 

- app.config is not a usual configuration source for .NET core anymore. I have not used akka under .NET myself. So I'm not aware what the best usage pattern should be for now in Akka.NET regarding configs either. So I have just included the hocon as a plain string. Hope it will be corrected from mainainers.
- there are surely some differences how threading is handled in 4.5 and .NET Core. I was concentrated to keep the lessons working. Also I have not found any exception mentions in Lesson 1 you writing about.

**Comment by vilinski** [comment]
Great news! Thanks to @Arkatufus the work is done in #315.

**Comment by Aaronontheweb** [comment]
thank YOU @vilinski - couldn't have done it without your help. We opted to do .NET Core 3.1 since it's stable, but we will happily port this to .NET 5 when it RTMs later this month hopefully.

**Pull request closed without merging**
