### PR TITLE
Added F# solution for lesson 2.1

### PR DESCRIPTION
**Pull request by jorgef**
Added F# solutions for lessons 2.1 and 2.2

### CODE REVIEW

**Comment by kjellski** [comment]
:+1: I love this, maybe we could introduce the whole series in F# too? I've just started looking into F# but I'd like to help if possible...

**Comment by Aaronontheweb** [comment]
@jorgef thanks so much for this!

@kjellski yes, we would love to do that - @skotzko and I don't know F# very well ourselves (working on it!) but would love to bring this to the F# community ASAP. Any help we can get translating solution files and READMEs to F# would be appreciated!

**Comment by skotzko** [comment]
@kjellski +1 to that. As @Aaronontheweb said, we don't know F# well enough to do the translation ourselves, but since Akka.NET has full F# support it deserves a track in that language. Any/all help very much appreciated!

**Comment by skotzko** [comment]
Thank you for your contribution, @jorgef !

**Pull request merged**
