### PR TITLE
Updated F# bootcamp folders and README to reflect structure of C# bootcamp

### PR DESCRIPTION
**Pull request by Youenn-Bouglouan**
Hi @Aaronontheweb, as discussed before I started to update the F# bootcamp so it follows the same structure as the C# one. Here are the structural changes I made for **Unit 2**:

- **Lesson 1**: changed the README only.

- **Lesson 2** was missing, so I created it by copying Lesson 1 and adding the C# README file to it.
So it's basically just a placeholder so far, I'll port it to F# in another PR.

- Renamed **Lesson 2** to Lesson 3 and updated the references in the README file accordingly.

- Renamed **Lesson 3** to Lesson 4 and updated the references in the README file accordingly.

- Renamed **Lesson 4** to Lesson 5 and updated the references in the README file accordingly.

So the "only" thing remaining now is to go over all those lessons and make sure they're up-to-date with their C# equivalent. I hope I'll manage to do that by the end of the week.

### CODE REVIEW

**Comment by Youenn-Bouglouan** [comment]
I forgot to update the main README for Unit 2, fixed this in the last commit.

**Comment by Aaronontheweb** [comment]
we should probably try to follow the same folder structure that Unit 1 has - keep FSharp and CSharp in two separate folders. That will make it much easier to merge them in together when it comes time to publish the entire F# course. Does that make sense?

**Comment by Youenn-Bouglouan** [comment]
@Aaronontheweb I understand what you mean. Ultimately I guess it depends on how we want to present the whole bootcamp. Do we want:
1. a single **master** branch with both CSharp and FSharp courses available as separate folders (the same as Unit 1 in the FSharp branch). Please note that the C# bootcamp handles it differently, so I'm not sure it will make it easier to merge.
2. two separate branches (**master** for C# and **FSharp** for F#), each with their own bootcamp. Basically the same as it is now.

**Pros of solution 1:**
- from a F# user perspective, everything would be available under **master**, so no more switching to the **FSharp** branch.
- 1 branch only, so in theory it will be easier to make changes to both bootcamps at the same time (though we should not assume it will automatically be the case).

**Cons of solution 1:**
- we'll have to go over each README file in **both** C# and F# bootcamps to update all the paths!
- there will be a bit more clicking through the folder structure involved (1 more level of depth).
- 1 branch only, so C# and F# commits will be all entangled. And it is still possible to have discrepancies between both versions.

**Pros of solution 2:**
- less work involved (no need to merge both bootcamps together and change all the paths accordingly).
- makes it more obvious that there might be slight differences between the F# and C# bootcamp.

**Cons of solution 2:**
- the F# bootcamp is not as visible, though this might probably be solved by putting a link to the F# README inside the main C# README (?)

What do you think about it?
Anyway, I think this is something we can deal with later, when I'm done with updating the F# bootcamp as it is.

**Comment by Aaronontheweb** [comment]
@Youenn-Bouglouan good question....

We should keep the two on separate branches and have the master README link to one track for FSharp and another for CSharp... I think that's the cleanest mode of separation for the two

**Comment by Youenn-Bouglouan** [comment]
Cool then, I think it's the best option too.

**Pull request closed without merging**
