### PR TITLE
Ported Unit 2 / Lesson 2 from C# to F#

### PR DESCRIPTION
**Pull request by Youenn-Bouglouan**
Warning: this builds on the changes submitted in #229 (thus the commits below). Please merge #229 first.

It looks like I'm done with Unit 2 / Lesson 2, took me longer than I first anticipated.
What changed:

- upgraded to Akka.FSharp 1.2.0
- rewrote most of the C# README.
- Show how to use the ReceiveActor in F#, but also show how to replace it by standard pattern matching + 'with' keyword.
- ported the whole C# exercise to F# (was missing from the F# bootcamp).

As a side effect, now I should be able to simplify Lesson 3. Because Lesson 2 was missing, there was lot of a code introduced 'out of nowhere' in this lesson 3. Those changes will allow us to make a smoother transition.

### CODE REVIEW

**Comment by Youenn-Bouglouan** [comment]
@Aaronontheweb let's try to merge https://github.com/petabridge/akka-bootcamp/pull/229, https://github.com/petabridge/akka-bootcamp/pull/230 and https://github.com/petabridge/akka-bootcamp/pull/231 before going further. I anticipate some changes in Unit 2 / Lesson 3 based on those, so better start fresh :). Thanks!

**Comment by Aaronontheweb** [comment]
@Youenn-Bouglouan will do - we have some merge conflicts here though since I merged in your previous PR. Would you mind rebasing? You can do it after I merge #229, but see my comments there also

**Comment by Youenn-Bouglouan** [comment]
@Aaronontheweb sure, I'll try to rebase https://github.com/petabridge/akka-bootcamp/pull/231 . The good news is that you don't need to merge https://github.com/petabridge/akka-bootcamp/pull/229 anymore as https://github.com/petabridge/akka-bootcamp/pull/230 was basing on it. The changes are already on the FSharp branch.

**Comment by Aaronontheweb** [comment]
so we can close #229?

**Comment by Youenn-Bouglouan** [comment]
It seems like it. The merge commit here https://github.com/petabridge/akka-bootcamp/commit/a050fe80d3b60baf0d6fe033d08c6cb2c07e1cd9 contains all changes already.

**Comment by Youenn-Bouglouan** [comment]
@Aaronontheweb I rebased and tested again the current PR, no more conflicts.

**Comment by Aaronontheweb** [comment]
Thanks, I'll review this!

**Comment by Youenn-Bouglouan** [comment]
Does it look good so far? I should be able to upload lesson 3 right after, provided there aren't too many changes needed here.

**Comment by Aaronontheweb** [comment]
@Youenn-Bouglouan looks great!

**Pull request merged**
