### PR TITLE
F sharp

### PR DESCRIPTION
**Pull request by johnazariah**
OK - it's now rebased against F#, and we are pulling into F#

### CODE REVIEW

**Comment by Aaronontheweb** [comment]
Do you want to include the FSharp syntax highlighting in this PR or will you do it subsequently?

**Comment by skotzko** [comment]
Also suggest adding separate links for the C# & F# code paths on the [main repo README](https://github.com/petabridge/akka-bootcamp). So user's on overview page can click into the track they want.

**Comment by johnazariah** [comment]
I've had to step away. I can merge it in a subsequent PR if it's all the same to you!

-----Original Message-----

**Comment by Aaronontheweb** [comment]
I'll pull this in now - we can do these updates in a subsequent PR.

**Pull request merged**
