### PR TITLE
Fixed lesson 2 sample bug causing a double Console.Readline

### PR DESCRIPTION
**Pull request by RyanHauert**

### CODE REVIEW

**Comment by mj1856** [comment]
:+1:

**Comment by mkmurray** [comment]
Pull requests on-the-fly to workshop presentation FTW! :+1:

**Comment by bennage** [comment]
:shipit:

**Comment by mkmurray** [comment]
The bug existed because when input was invalid, two messages (validation error and continue processing) were sent back to itself and got queued up, causing two Console.ReadLine calls in a row. For the fix, we moved it into the success validation branch of the if statement so that both branches of the condition had only one message sent back to itself in order to restart the OnReceive method and Console.ReadLine again.

**Comment by skotzko** [comment]
this is awesome. thank you!

**Pull request merged**
